name:                recschemes
version:             0.1.0.0
github:              "dbalseiro/recschemes"
license:             BSD3
author:              "Author name here"
maintainer:          "dbalseiro@gmail.com"
copyright:           "2022 Diego Balseiro"

extra-source-files:
- README.md
- CHANGELOG.md

description: Recursion Schemes tinkering project

dependencies:
- base >= 4.7 && < 5
- unordered-containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - text
  - megaparsec
  - data-fix
  - hashable
  - containers
  - mtl
  - aeson
  - vector

tests:
  recschemes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - recschemes
    - hspec
